### ISSUE TITLE
Iugi com Php

### ISSUE THREAD

**Issue by OliveiraMrw** [iugu/iugu-php#16]
Boa tarde pessoal, tudo bem ?

Estou tentando fazer minhas primeiras integrações com do Iugu + Php, porém não estou conseguindo, vem retornando erros que não encontrei na net ainda respostas.

Baixei a biblioteca indicada pelo suporte, e na primeira tentativa de listas as faturas retorna este erro :+1: 

Fatal error: Call to a member function results() on a non-object in /var/www/vhost

este é o código 
-----------------------------------
error_reporting( E_ALL );
ini_set("display_errors", 1);

require_once("Iugu.php");

echo "01<br>"; 

Iugu::setApiKey("API_KEY");

echo "02<br>"; 

$invoices = Iugu_Invoice::search()->results();

echo "03<br>"; 

		echo "<pre>01<br>";
		echo print_r($invoices);
		die("</pre>");

-------------------------------------------------------
 
Também tentei via curl, e retorna o erro "errors":"Not Found"}, o código é este
------------------------------------------
		$dados = array( "api_token"	=> 'API_KEY' );

		$ch = curl_init("https://api.iugu.com/v1/invoices/410125B4A5A84EAFACBE7F988AB369B1");
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, array_map('utf8_encode', $dados)  );
//		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

		$output = curl_exec($ch);
		curl_close($ch);

		echo "<pre>";
		echo print_r($output);
		die("</pre>");

------------------------------------------

Alguém pode auxiliar ?

**Comment by andrekutianski** [comment]
Olá @OliveiraMrw você está seguindo a documentação da Iugu? Lá você poderá encontrar informações e códigos de exemplos para trabalhar com a API e esta biblioteca (são bem explicados por sinal).

Você poderá encontrar a documentação de desenvolvimento no novo endereço: [https://dev.iugu.com/docs](https://dev.iugu.com/docs)

**Comment by lucasprag** [comment]
Oi @OliveiraMrw , perdão pelo atraso na resposta, nós não mantemos um olho constante nas issues dos projetos ainda, mas nós temos uma equipe de suporte via chat que pode te ajudar com essas e outras dúvidas.

Obrigado @andrekutianski por responder a issue.

Obrigado pessoal =)
