### ISSUE TITLE
Alterar, Duplicar ou Cancelar fatura.

### ISSUE THREAD

**Issue by osmarzito** [iugu/iugu-php#19]
Boa tarde pessoal, alguém sabe como faço para alterar uma fatura já cadastrada utilizando os métodos da api, como faço para atribuir o id da fatura para alterá-la?

Obrigado.

**Comment by arturcesarmelo** [comment]
```php
$dados = [
    'due_date' => date('d/m/Y')
];

if (count($subitens)) {
    $dados['items'] = $subitens;
}

$invoice = $iuguInvoice->duplicate($invoice->id, $dados);
```

**Comment by lucasprag** [comment]
Oi @osmarzito , perdão pelo atraso na resposta, nós não mantemos um olho constante nas issues dos projetos ainda, mas nós temos uma equipe de suporte via chat que pode te ajudar com essas e outras dúvidas.

Obrigado @arturcesarmelo por responder o Osmar.

Obrigado pessoal =)
