### ISSUE TITLE
Customer Not Found

### ISSUE THREAD

**Issue by LCPGomescode** [iugu/iugu-php#20]
biblioteca PHP
criar plano

`$return = Iugu_Plan::create(Array(
						"name"          => "Personalizado ".$np['Pedido']['preco_total'],
						"identifier" 	=> $plan_identifier,						
						"interval"		=> "30",
						"interval_type" => "months",
						"prices"		=> (float) $np['Pedido']['preco_total'] * 100, //transforma em centavos
						
					));	
					$coisa = $return->save();`

string(31) "{"errors":"Customer Not Found"}"

como resolver este erro?

**Comment by lucasprag** [comment]
Oi @LCPGomescode 
Esse não é um erro da biblioteca, você poderia entrar em contato com a nossa equipe de suporte pelo painel? Tem um chat la e eles te ajudam com esse problema.

Obrigado =)
