### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by gabrielkoerich** [iugu/iugu-php#25]
A última tag do projeto foi criada em 2015 

Não é muito seguro usar dev-master em produção, poderiam gerar tags a cada nova atualização com testes? 

Ainda estou usando a versão ~1 e está bem desatualizada.

Obrigado

**Comment by MiguelAlcaino** [comment]
I just pushed a forked version to packagist with the latest updates. `composer require miguelalcaino/iugu`

**Comment by raulamoretti** [comment]
Pessoal no aguardo de updates da biblioteca!
