### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by jansenfelipe** [iugu/iugu-php#61]
Está com problema no certificado .. comentei as linhas 110, 111, 112 e funcionou ...

![image](https://github.com/iugu/iugu-php/assets/3134214/c093124b-4290-42d8-a5d7-71f00cfa8465)

**Comment by pnegri** [comment]
Boa, mudou a cadeia da cloudflare (deixaram de operar com digicert)

**Comment by pnegri** [comment]
Cadeia atualizada e versão atualizada no packagist. 1.0.7
