### ISSUE TITLE
throw new IuguRequestException

### ISSUE THREAD

**Issue by sudeste** [iugu/iugu-php#7]
Eu posso está enganado mas acho que o código abaixo tem um erro.

```
if (isset($response->errors)) throw IuguRequestException( $response->errors );
```
Está faltando o "new"
Aqui está a linha:
https://github.com/iugu/iugu-php/blob/master/lib/Iugu/Invoice.php#L26

**Comment by pnegri** [comment]
Corrigido. Obrigado.
